[build]
  command = "npm run build --prefix client"
  publish = "client/build"

[build.environment]
  REACT_APP_API_URL = "https://amazon-clone-api-2vgt.onrender.com/api"
  REACT_APP_GOOGLE_CLIENT_ID = "320172624128-7ggdtsb0cevqfet3ikus15lpivjk777t.apps.googleusercontent.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {NOT = [{header = "accept", value = "application/json"}]}
